// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Box", b =>
                {
                    b.Property<string>("BoxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("box_id");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("IdChar")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id_char");

                    b.Property<int>("IdNum")
                        .HasColumnType("integer")
                        .HasColumnName("id_num");

                    b.Property<int>("MPrice")
                        .HasColumnType("integer")
                        .HasColumnName("m_price");

                    b.Property<int>("MValue")
                        .HasColumnType("integer")
                        .HasColumnName("m_value");

                    b.Property<string>("Mm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mm");

                    b.Property<string>("Purity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purity");

                    b.Property<string>("Shape1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shape1");

                    b.Property<string>("Shape2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shape2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BoxId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("boxes");
                });

            modelBuilder.Entity("backend.Models.BoxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("box_id");

                    b.Property<string>("PolishLotId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polish_lot_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("PolishLotId");

                    b.ToTable("boxitems");
                });

            modelBuilder.Entity("backend.Models.BoxSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("bill_amount");

                    b.Property<decimal>("BillPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bill_percentage");

                    b.Property<int>("CashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cash_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_type");

                    b.Property<int?>("DalalId")
                        .HasColumnType("integer")
                        .HasColumnName("dalal_id");

                    b.Property<decimal>("Dalali")
                        .HasColumnType("numeric")
                        .HasColumnName("dalali");

                    b.Property<int>("DalaliAmount")
                        .HasColumnType("integer")
                        .HasColumnName("dalali_amount");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<int>("DeadlineDays")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_days");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int>("DiscountedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_amount");

                    b.Property<decimal?>("DollarRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dollar_rate");

                    b.Property<int>("FinalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("final_amount");

                    b.Property<int>("Gst")
                        .HasColumnType("integer")
                        .HasColumnName("gst");

                    b.Property<int>("NetBillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_bill_amount");

                    b.Property<int>("NetCashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_cash_amount");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<DateTime>("SellingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selling_date");

                    b.Property<int>("SellingNo")
                        .HasColumnType("integer")
                        .HasColumnName("selling_no");

                    b.Property<int?>("TotalDollar")
                        .HasColumnType("integer")
                        .HasColumnName("total_dollar");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DalalId");

                    b.HasIndex("PartyId");

                    b.ToTable("boxsales");
                });

            modelBuilder.Entity("backend.Models.BoxSaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("box_id");

                    b.Property<int>("BoxSaleId")
                        .HasColumnType("integer")
                        .HasColumnName("box_sale_id");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<int>("MPrice")
                        .HasColumnType("integer")
                        .HasColumnName("m_price");

                    b.Property<int>("MValue")
                        .HasColumnType("integer")
                        .HasColumnName("m_value");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("BoxSaleId");

                    b.ToTable("boxsaleitems");
                });

            modelBuilder.Entity("backend.Models.Conversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conversion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("PolishPieces")
                        .HasColumnType("integer")
                        .HasColumnName("polish_pieces");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<int>("RoughPieces")
                        .HasColumnType("integer")
                        .HasColumnName("rough_pieces");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("conversions");
                });

            modelBuilder.Entity("backend.Models.PartyMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("partymaster");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int?>("BoxSaleId")
                        .HasColumnType("integer")
                        .HasColumnName("box_sale_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("payment_type");

                    b.Property<string>("PolishLotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polish_lot_id");

                    b.Property<int?>("PolishSaleId")
                        .HasColumnType("integer")
                        .HasColumnName("polish_sale_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<int?>("RoughBuyId")
                        .HasColumnType("integer")
                        .HasColumnName("rough_buy_id");

                    b.Property<int?>("RoughSaleId")
                        .HasColumnType("integer")
                        .HasColumnName("rough_sale_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BoxSaleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PolishLotId");

                    b.HasIndex("PolishSaleId");

                    b.HasIndex("RoughBuyId");

                    b.HasIndex("RoughSaleId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("backend.Models.PolishLot", b =>
                {
                    b.Property<string>("LotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lot_id");

                    b.Property<int?>("BillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("bill_amount");

                    b.Property<decimal?>("BillPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bill_percentage");

                    b.Property<DateTime>("BuyingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buying_date");

                    b.Property<int?>("BuyingNo")
                        .HasColumnType("integer")
                        .HasColumnName("buying_no");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<int?>("CashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cash_amount");

                    b.Property<int?>("ConversionId")
                        .HasColumnType("integer")
                        .HasColumnName("conversion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_type");

                    b.Property<int?>("DalalId")
                        .HasColumnType("integer")
                        .HasColumnName("dalal_id");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<int?>("DeadlineDays")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_days");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int?>("DiscountedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_amount");

                    b.Property<decimal?>("DollarRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dollar_rate");

                    b.Property<int?>("FinalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("final_amount");

                    b.Property<int?>("Gst")
                        .HasColumnType("integer")
                        .HasColumnName("gst");

                    b.Property<int?>("NetBillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_bill_amount");

                    b.Property<int?>("NetCashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_cash_amount");

                    b.Property<int?>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer")
                        .HasColumnName("pieces");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int?>("TotalDollar")
                        .HasColumnType("integer")
                        .HasColumnName("total_dollar");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LotId");

                    b.HasIndex("ConversionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DalalId");

                    b.HasIndex("PartyId");

                    b.ToTable("polishlots");
                });

            modelBuilder.Entity("backend.Models.PolishSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("bill_amount");

                    b.Property<decimal>("BillPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bill_percentage");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<int>("CashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cash_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_type");

                    b.Property<int?>("DalalId")
                        .HasColumnType("integer")
                        .HasColumnName("dalal_id");

                    b.Property<decimal>("Dalali")
                        .HasColumnType("numeric")
                        .HasColumnName("dalali");

                    b.Property<int>("DalaliAmount")
                        .HasColumnType("integer")
                        .HasColumnName("dalali_amount");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<int>("DeadlineDays")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_days");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int>("DiscountedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_amount");

                    b.Property<decimal?>("DollarRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dollar_rate");

                    b.Property<int>("FinalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("final_amount");

                    b.Property<int>("Gst")
                        .HasColumnType("integer")
                        .HasColumnName("gst");

                    b.Property<string>("IssueNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("issue_no");

                    b.Property<string>("LotId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lot_id");

                    b.Property<int>("NetBillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_bill_amount");

                    b.Property<int>("NetCashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_cash_amount");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer")
                        .HasColumnName("pieces");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<DateTime>("SellingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selling_date");

                    b.Property<int>("SellingNo")
                        .HasColumnType("integer")
                        .HasColumnName("selling_no");

                    b.Property<string>("SourceLocation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_location");

                    b.Property<int?>("TotalDollar")
                        .HasColumnType("integer")
                        .HasColumnName("total_dollar");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DalalId");

                    b.HasIndex("PartyId");

                    b.ToTable("polishsales");
                });

            modelBuilder.Entity("backend.Models.RoughBuy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("bill_amount");

                    b.Property<decimal>("BillPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bill_percentage");

                    b.Property<DateTime>("BuyingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buying_date");

                    b.Property<int>("BuyingNo")
                        .HasColumnType("integer")
                        .HasColumnName("buying_no");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<int>("CashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cash_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_type");

                    b.Property<int?>("DalalId")
                        .HasColumnType("integer")
                        .HasColumnName("dalal_id");

                    b.Property<decimal>("Dalali")
                        .HasColumnType("numeric")
                        .HasColumnName("dalali");

                    b.Property<int>("DalaliAmount")
                        .HasColumnType("integer")
                        .HasColumnName("dalali_amount");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<int>("DeadlineDays")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_days");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int>("DiscountedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_amount");

                    b.Property<decimal?>("DollarRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dollar_rate");

                    b.Property<int>("FinalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("final_amount");

                    b.Property<int>("Gst")
                        .HasColumnType("integer")
                        .HasColumnName("gst");

                    b.Property<int>("NetBillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_bill_amount");

                    b.Property<int>("NetCashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_cash_amount");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer")
                        .HasColumnName("pieces");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int?>("TotalDollar")
                        .HasColumnType("integer")
                        .HasColumnName("total_dollar");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DalalId");

                    b.HasIndex("PartyId");

                    b.ToTable("roughbuys");
                });

            modelBuilder.Entity("backend.Models.RoughSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("bill_amount");

                    b.Property<decimal>("BillPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bill_percentage");

                    b.Property<decimal>("Carat")
                        .HasColumnType("numeric")
                        .HasColumnName("carat");

                    b.Property<int>("CashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cash_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_type");

                    b.Property<int?>("DalalId")
                        .HasColumnType("integer")
                        .HasColumnName("dalal_id");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<int>("DeadlineDays")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_days");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int>("DiscountedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_amount");

                    b.Property<decimal?>("DollarRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dollar_rate");

                    b.Property<int>("FinalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("final_amount");

                    b.Property<int>("Gst")
                        .HasColumnType("integer")
                        .HasColumnName("gst");

                    b.Property<int>("NetBillAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_bill_amount");

                    b.Property<int>("NetCashAmount")
                        .HasColumnType("integer")
                        .HasColumnName("net_cash_amount");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer")
                        .HasColumnName("pieces");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<DateTime>("SellingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selling_date");

                    b.Property<int>("SellingNo")
                        .HasColumnType("integer")
                        .HasColumnName("selling_no");

                    b.Property<int?>("TotalDollar")
                        .HasColumnType("integer")
                        .HasColumnName("total_dollar");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DalalId");

                    b.HasIndex("PartyId");

                    b.ToTable("roughsales");
                });

            modelBuilder.Entity("backend.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_location");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("item_type");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_location");

                    b.Property<string>("TransferNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transfer_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("transfers");
                });

            modelBuilder.Entity("backend.Models.TransferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("box_id");

                    b.Property<string>("PolishLotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polish_lot_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("TransferId")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("PolishLotId");

                    b.HasIndex("TransferId");

                    b.ToTable("transferitems");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.VendorIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("IssueNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("issue_no");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VendorId");

                    b.ToTable("vendorissues");
                });

            modelBuilder.Entity("backend.Models.VendorIssueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("box_id");

                    b.Property<int>("IssueId")
                        .HasColumnType("integer")
                        .HasColumnName("issue_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("item_type");

                    b.Property<string>("PolishLotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polish_lot_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("IssueId");

                    b.HasIndex("PolishLotId");

                    b.ToTable("vendorissueitems");
                });

            modelBuilder.Entity("backend.Models.VendorMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VendorNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vendor_no");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vendor_type");

                    b.HasKey("Id");

                    b.ToTable("vendormaster");
                });

            modelBuilder.Entity("backend.Models.Box", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Models.BoxItem", b =>
                {
                    b.HasOne("backend.Models.Box", "Box")
                        .WithMany("BoxItems")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PolishLot", "PolishLot")
                        .WithMany()
                        .HasForeignKey("PolishLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("PolishLot");
                });

            modelBuilder.Entity("backend.Models.BoxSale", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Dalal")
                        .WithMany()
                        .HasForeignKey("DalalId");

                    b.HasOne("backend.Models.PartyMaster", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Dalal");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("backend.Models.BoxSaleItem", b =>
                {
                    b.HasOne("backend.Models.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.BoxSale", "BoxSale")
                        .WithMany("SaleItems")
                        .HasForeignKey("BoxSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("BoxSale");
                });

            modelBuilder.Entity("backend.Models.Conversion", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.HasOne("backend.Models.BoxSale", "BoxSale")
                        .WithMany("Payments")
                        .HasForeignKey("BoxSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.PolishLot", "PolishLot")
                        .WithMany("Payments")
                        .HasForeignKey("PolishLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.PolishSale", "PolishSale")
                        .WithMany("Payments")
                        .HasForeignKey("PolishSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.RoughBuy", "RoughBuy")
                        .WithMany("Payments")
                        .HasForeignKey("RoughBuyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.RoughSale", "RoughSale")
                        .WithMany("Payments")
                        .HasForeignKey("RoughSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoxSale");

                    b.Navigation("Creator");

                    b.Navigation("PolishLot");

                    b.Navigation("PolishSale");

                    b.Navigation("RoughBuy");

                    b.Navigation("RoughSale");
                });

            modelBuilder.Entity("backend.Models.PolishLot", b =>
                {
                    b.HasOne("backend.Models.Conversion", "Conversion")
                        .WithMany()
                        .HasForeignKey("ConversionId");

                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Dalal")
                        .WithMany()
                        .HasForeignKey("DalalId");

                    b.HasOne("backend.Models.PartyMaster", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId");

                    b.Navigation("Conversion");

                    b.Navigation("Creator");

                    b.Navigation("Dalal");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("backend.Models.PolishSale", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Dalal")
                        .WithMany()
                        .HasForeignKey("DalalId");

                    b.HasOne("backend.Models.PartyMaster", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Dalal");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("backend.Models.RoughBuy", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Dalal")
                        .WithMany()
                        .HasForeignKey("DalalId");

                    b.HasOne("backend.Models.PartyMaster", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Dalal");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("backend.Models.RoughSale", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Dalal")
                        .WithMany()
                        .HasForeignKey("DalalId");

                    b.HasOne("backend.Models.PartyMaster", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Dalal");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("backend.Models.Transfer", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Models.TransferItem", b =>
                {
                    b.HasOne("backend.Models.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId");

                    b.HasOne("backend.Models.PolishLot", "PolishLot")
                        .WithMany()
                        .HasForeignKey("PolishLotId");

                    b.HasOne("backend.Models.Transfer", "Transfer")
                        .WithMany("Items")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("PolishLot");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("backend.Models.VendorIssue", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("backend.Models.VendorMaster", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("backend.Models.VendorIssueItem", b =>
                {
                    b.HasOne("backend.Models.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId");

                    b.HasOne("backend.Models.VendorIssue", "VendorIssue")
                        .WithMany("Items")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.PolishLot", "PolishLot")
                        .WithMany()
                        .HasForeignKey("PolishLotId");

                    b.Navigation("Box");

                    b.Navigation("PolishLot");

                    b.Navigation("VendorIssue");
                });

            modelBuilder.Entity("backend.Models.Box", b =>
                {
                    b.Navigation("BoxItems");
                });

            modelBuilder.Entity("backend.Models.BoxSale", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("backend.Models.PolishLot", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.PolishSale", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.RoughBuy", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.RoughSale", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.Transfer", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("backend.Models.VendorIssue", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
